>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> print(lazy_matrix_mul([[5, 6]], [[9, 2], [3, 7]])
[[63 52]]

>>> print(lazy_matrix_mul([[1, 2], [3, 5]], [[1, 2], [3, 7]]))
[[ 7 16]
 [18 41]]

>>> print(lazy_matrix_mul([[1.0, 2.0], [3.0, 4.0]], [[1.0, 2], [3, 4]]))
[[ 7. 10.]
 [15. 22.]]

>>> print(lazy_matrix_mul([[1.0, 2.0], [3.0, 4.0]]))
Traceback (most recent call last):
    ...
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> print(lazy_matrix_mul())
Traceback (most recent call last):
    ...
TypeError: lazy_matrix_mul() missing 1 required positional argument:
'm_a' and 'm_b'

>>> print(lazy_matrix_mul([[1.0, 2.0], [3.0, 4.0]], [3, 5]], [[1, 2], [3, 7]]))
Traceback (most recent call last):
    ...
ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

>>> print(lazy_matrix_mul([[]], [[9, 2], [3, 4]]))
Traceback (most recent call last):
    ...
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

>>> print(lazy_matrix_mul([[1, 3], [2, 6]], [[]]))
Traceback (most recent call last):
    ...
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> print(lazy_matrix_mul("Hola", [[1, 2]]))
Traceback (most recent call last)
    ...
ValueError: Scalar operands are not allowed, use '*' instead

>>> print(lazy_matrix_mul([[1, 2]], "crack"))
Traceback (most recent call last):
    ...
ValueError: Scalar operands are not allowed, use '*' instead

>>> print(lazy_matrix_mul("Fiera", "maquina"))
Traceback (most recent call last):
    ...
ValueError: Scalar operands are not allowed, use '*' instead

>>> print(lazy_matrix_mul(None, None))
Traceback (most recent call last):
    ...
TypeError: Object arrays are not currently supported

>>> print(lazy_matrix_mul([5, 6], [[3, 4]]))
Traceback (most recent call last):
    ...
ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)

>>> print(lazy_matrix_mul([[1, "hhh"]], [[{"a": 1}, 9.5]]))
Traceback (most recent call last):
    ...
TypeError: Object arrays are not currently supported

>>> print(lazy_matrix_mul([[4, 5], [7, 8, 9]], [[3, 4], [8, 9]]))
Traceback (most recent call last):
    ...
ValueError: setting an array element with a sequence.

>>> print(lazy_matrix_mul([[3, 4], [8, 9]], [[4, 5], [7, 8, 9]]))
Traceback (most recent call last):
    ...
ValueError: setting an array element with a sequence.

>>> matrix_mul([["holberton", 5], [6, 9]], [[7, 8], [5, 2]])
Traceback (most recent call last):
    ...
TypeError: invalid data type for einsum
